CREATE TABLE `certificate_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`certificateTitle` varchar(200) NOT NULL DEFAULT 'Blind Installation Certificate',
	`headerCompanyName` varchar(200) NOT NULL DEFAULT 'Shedgum Gas Plant',
	`headerSubtitle` varchar(300) NOT NULL DEFAULT 'Smart Blind Tracking System - SBTS',
	`logoUrl` text,
	`signature1Label` varchar(100) NOT NULL DEFAULT 'Prepared By',
	`signature1Name` varchar(160),
	`signature1Title` varchar(160),
	`signature2Label` varchar(100) NOT NULL DEFAULT 'Reviewed By',
	`signature2Name` varchar(160),
	`signature2Title` varchar(160),
	`signature3Label` varchar(100) NOT NULL DEFAULT 'Approved By',
	`signature3Name` varchar(160),
	`signature3Title` varchar(160),
	`footerText` text,
	`showPageNumbers` int NOT NULL DEFAULT 1,
	`showGenerationDate` int NOT NULL DEFAULT 1,
	`showSystemVersion` int NOT NULL DEFAULT 1,
	`paperSize` varchar(20) NOT NULL DEFAULT 'A4',
	`orientation` varchar(20) NOT NULL DEFAULT 'portrait',
	`updatedByOpenId` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `certificate_settings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `default_tag_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tagPrefix` varchar(20) NOT NULL DEFAULT 'BLD',
	`tagSeparator` varchar(5) NOT NULL DEFAULT '-',
	`tagPaddingDigits` int NOT NULL DEFAULT 3,
	`tagStartNumber` int NOT NULL DEFAULT 1,
	`defaultType` varchar(120) NOT NULL DEFAULT 'Spectacle Blind',
	`defaultSize` varchar(60) NOT NULL DEFAULT '2"',
	`defaultRate` varchar(60) NOT NULL DEFAULT '150#',
	`blindPriority` enum('Low','Normal','High','Critical') NOT NULL DEFAULT 'Normal',
	`blindPhase` enum('Broken / Preparation','Assembly','Tight & Torque','Final Tight','Inspection Ready') NOT NULL DEFAULT 'Broken / Preparation',
	`autoGenerateTag` int NOT NULL DEFAULT 1,
	`requireEquipment` int NOT NULL DEFAULT 0,
	`requireLocation` int NOT NULL DEFAULT 0,
	`requireIsolationPoint` int NOT NULL DEFAULT 0,
	`updatedByOpenId` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `default_tag_settings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `system_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyName` varchar(200) NOT NULL DEFAULT 'Shedgum Gas Plant',
	`companyCode` varchar(40) NOT NULL DEFAULT 'SGP',
	`plantName` varchar(200) NOT NULL DEFAULT 'Shedgum Gas Plant',
	`contractNumber` varchar(100),
	`language` varchar(10) NOT NULL DEFAULT 'en',
	`timezone` varchar(80) NOT NULL DEFAULT 'Asia/Riyadh',
	`dateFormat` varchar(40) NOT NULL DEFAULT 'DD/MM/YYYY',
	`emailNotifications` int NOT NULL DEFAULT 1,
	`phaseChangeAlerts` int NOT NULL DEFAULT 1,
	`criticalPriorityAlerts` int NOT NULL DEFAULT 1,
	`systemVersion` varchar(40) NOT NULL DEFAULT '1.0.0',
	`maintenanceMode` int NOT NULL DEFAULT 0,
	`updatedByOpenId` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `system_settings_id` PRIMARY KEY(`id`)
);
