/**
 * useCertificateSettings Hook
 * Fetches certificate settings from the server and provides them to report components.
 * Used by all report components to automatically apply logo, signatures, and print settings.
 */
import { trpc } from "@/lib/trpc";

export interface CertificateSettingsData {
  certificateTitle: string;
  headerCompanyName: string;
  headerSubtitle: string;
  logoUrl: string | null;
  footerText: string | null;
  paperSize: "A4" | "A3" | "Letter" | "Legal";
  orientation: "portrait" | "landscape";
  showPageNumbers: boolean;
  showGenerationDate: boolean;
  showSystemVersion: boolean;
  signature1Label: string;
  signature1Name: string | null;
  signature1Title: string | null;
  signature2Label: string;
  signature2Name: string | null;
  signature2Title: string | null;
  signature3Label: string;
  signature3Name: string | null;
  signature3Title: string | null;
}

export const DEFAULT_CERTIFICATE_SETTINGS: CertificateSettingsData = {
  certificateTitle: "Blind Installation Certificate",
  headerCompanyName: "Shedgum Gas Plant",
  headerSubtitle: "Smart Blind Tracking System - SBTS",
  logoUrl: null,
  footerText: "This certificate is system-generated by SBTS - Smart Blind Tracking System.",
  paperSize: "A4",
  orientation: "portrait",
  showPageNumbers: true,
  showGenerationDate: true,
  showSystemVersion: true,
  signature1Label: "Prepared By",
  signature1Name: null,
  signature1Title: null,
  signature2Label: "Reviewed By",
  signature2Name: null,
  signature2Title: null,
  signature3Label: "Approved By",
  signature3Name: null,
  signature3Title: null,
};

/**
 * Fetches certificate settings from the server.
 * Falls back to DEFAULT_CERTIFICATE_SETTINGS if no settings are saved yet.
 */
export function useCertificateSettings() {
  const { data, isLoading, error } = trpc.settings.certificate.get.useQuery(undefined, {
    staleTime: 5 * 60 * 1000, // Cache for 5 minutes
    retry: 1,
  });

  const settings: CertificateSettingsData = data
    ? {
        certificateTitle: data.certificateTitle ?? DEFAULT_CERTIFICATE_SETTINGS.certificateTitle,
        headerCompanyName: data.headerCompanyName ?? DEFAULT_CERTIFICATE_SETTINGS.headerCompanyName,
        headerSubtitle: data.headerSubtitle ?? DEFAULT_CERTIFICATE_SETTINGS.headerSubtitle,
        logoUrl: data.logoUrl ?? null,
        footerText: data.footerText ?? DEFAULT_CERTIFICATE_SETTINGS.footerText,
        paperSize: (data.paperSize as CertificateSettingsData["paperSize"]) ?? DEFAULT_CERTIFICATE_SETTINGS.paperSize,
        orientation: (data.orientation as CertificateSettingsData["orientation"]) ?? DEFAULT_CERTIFICATE_SETTINGS.orientation,
        showPageNumbers: data.showPageNumbers === 1,
        showGenerationDate: data.showGenerationDate === 1,
        showSystemVersion: data.showSystemVersion === 1,
        signature1Label: data.signature1Label ?? DEFAULT_CERTIFICATE_SETTINGS.signature1Label,
        signature1Name: data.signature1Name ?? null,
        signature1Title: data.signature1Title ?? null,
        signature2Label: data.signature2Label ?? DEFAULT_CERTIFICATE_SETTINGS.signature2Label,
        signature2Name: data.signature2Name ?? null,
        signature2Title: data.signature2Title ?? null,
        signature3Label: data.signature3Label ?? DEFAULT_CERTIFICATE_SETTINGS.signature3Label,
        signature3Name: data.signature3Name ?? null,
        signature3Title: data.signature3Title ?? null,
      }
    : DEFAULT_CERTIFICATE_SETTINGS;

  return { settings, isLoading, error };
}

// ─── PDF Generation Utilities ─────────────────────────────────────────────────

/**
 * Returns CSS @page rule based on paper size and orientation.
 */
export function getPaperCSS(paperSize: string, orientation: string): string {
  const sizeMap: Record<string, string> = {
    A4: "210mm 297mm",
    A3: "297mm 420mm",
    Letter: "8.5in 11in",
    Legal: "8.5in 14in",
  };
  const size = sizeMap[paperSize] ?? sizeMap["A4"];
  return orientation === "landscape"
    ? `@page { size: ${size.split(" ").reverse().join(" ")}; margin: 15mm; }`
    : `@page { size: ${size}; margin: 15mm; }`;
}

/**
 * Builds the HTML header section for PDF reports using certificate settings.
 */
export function buildReportHeader(settings: CertificateSettingsData, reportTitle: string): string {
  const logoHtml =
    settings.logoUrl
      ? `<img src="${settings.logoUrl}" alt="Company Logo" style="height:60px;max-width:180px;object-fit:contain;" />`
      : "";

  return `
    <div class="report-header" style="
      display:flex;
      align-items:center;
      justify-content:space-between;
      padding-bottom:18px;
      border-bottom:3px solid #0f172a;
      margin-bottom:28px;
    ">
      <div style="flex:1;">
        <h1 style="margin:0;font-size:22px;font-weight:800;color:#0f172a;">${settings.certificateTitle}</h1>
        <h2 style="margin:6px 0 0 0;font-size:16px;font-weight:600;color:#334155;">${reportTitle}</h2>
        <div style="font-size:13px;color:#64748b;margin-top:4px;">${settings.headerCompanyName}</div>
        <div style="font-size:12px;color:#94a3b8;margin-top:2px;">${settings.headerSubtitle}</div>
      </div>
      ${logoHtml ? `<div style="margin-left:20px;">${logoHtml}</div>` : ""}
    </div>
  `;
}

/**
 * Builds the HTML signatures section for PDF reports using certificate settings.
 */
export function buildSignaturesSection(settings: CertificateSettingsData): string {
  const signatures = [
    { label: settings.signature1Label, name: settings.signature1Name, title: settings.signature1Title },
    { label: settings.signature2Label, name: settings.signature2Name, title: settings.signature2Title },
    { label: settings.signature3Label, name: settings.signature3Name, title: settings.signature3Title },
  ];

  const sigBlocks = signatures
    .map(
      (sig) => `
      <div style="flex:1;text-align:center;padding:0 10px;">
        <div style="
          border-top:2px solid #0f172a;
          padding-top:10px;
          margin-top:40px;
        ">
          <div style="font-size:13px;font-weight:700;color:#0f172a;">${sig.label}</div>
          ${sig.name ? `<div style="font-size:12px;color:#334155;margin-top:4px;">${sig.name}</div>` : ""}
          ${sig.title ? `<div style="font-size:11px;color:#64748b;margin-top:2px;">${sig.title}</div>` : ""}
        </div>
      </div>
    `
    )
    .join("");

  return `
    <div class="signatures-section" style="
      margin-top:40px;
      padding-top:20px;
      border-top:1px solid #e2e8f0;
    ">
      <div style="font-size:12px;font-weight:600;color:#64748b;margin-bottom:10px;text-transform:uppercase;letter-spacing:0.5px;">
        Signatures
      </div>
      <div style="display:flex;gap:20px;">
        ${sigBlocks}
      </div>
    </div>
  `;
}

/**
 * Builds the HTML footer section for PDF reports using certificate settings.
 */
export function buildReportFooter(settings: CertificateSettingsData): string {
  const footerText = settings.footerText ?? "This certificate is system-generated by SBTS.";
  const generatedLine = settings.showGenerationDate
    ? `<p style="margin:0 0 4px 0;">Generated: ${new Date().toLocaleString("en-SA", { timeZone: "Asia/Riyadh" })}</p>`
    : "";
  const systemLine = settings.showSystemVersion
    ? `<p style="margin:0;">SBTS - Smart Blind Tracking System</p>`
    : "";

  return `
    <div class="report-footer" style="
      margin-top:30px;
      padding-top:15px;
      border-top:1px solid #e2e8f0;
      text-align:center;
      color:#94a3b8;
      font-size:11px;
    ">
      <p style="margin:0 0 4px 0;">${footerText}</p>
      ${generatedLine}
      ${systemLine}
    </div>
  `;
}

/**
 * Opens a print window with the given HTML content, applying certificate settings.
 */
export function openPrintWindow(
  htmlBody: string,
  settings: CertificateSettingsData,
  reportTitle: string,
  windowTitle: string
): void {
  const printWindow = window.open("", "_blank", "noopener,noreferrer");
  if (!printWindow) return;

  const pageCSS = getPaperCSS(settings.paperSize, settings.orientation);
  const header = buildReportHeader(settings, reportTitle);
  const signatures = buildSignaturesSection(settings);
  const footer = buildReportFooter(settings);

  const fullHtml = `
    <!DOCTYPE html>
    <html dir="ltr" lang="en">
      <head>
        <meta charset="UTF-8" />
        <title>${windowTitle}</title>
        <style>
          ${pageCSS}
          * { box-sizing: border-box; }
          body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            background: white;
            color: #0f172a;
            font-size: 13px;
            line-height: 1.5;
          }
          table { width: 100%; border-collapse: collapse; }
          th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #e2e8f0; font-size: 12px; }
          th { background: #f1f5f9; font-weight: 700; color: #334155; text-transform: uppercase; letter-spacing: 0.4px; font-size: 11px; }
          tr:hover td { background: #f8fafc; }
          .section-title {
            background: #f1f5f9;
            padding: 8px 14px;
            border-left: 4px solid #0f172a;
            font-weight: 700;
            color: #0f172a;
            margin: 20px 0 12px 0;
            font-size: 13px;
          }
          .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 15px; }
          .info-item { background: #f8fafc; padding: 10px 14px; border-radius: 6px; border-left: 3px solid #0f172a; }
          .info-label { font-size: 11px; color: #64748b; margin-bottom: 4px; text-transform: uppercase; letter-spacing: 0.5px; }
          .info-value { font-size: 15px; font-weight: 700; color: #0f172a; }
          .badge { display: inline-block; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: 700; }
          .badge-blue { background: #e0f2fe; color: #0369a1; }
          .badge-green { background: #dcfce7; color: #15803d; }
          .badge-amber { background: #fef9c3; color: #a16207; }
          .badge-red { background: #fee2e2; color: #b91c1c; }
          .stats-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin: 15px 0; }
          .stat-card { background: #f8fafc; padding: 14px; border-radius: 6px; text-align: center; border: 1px solid #e2e8f0; }
          .stat-number { font-size: 22px; font-weight: 800; color: #0f172a; }
          .stat-label { font-size: 11px; color: #64748b; margin-top: 4px; }
          @media print { body { padding: 0; } .no-print { display: none !important; } }
        </style>
      </head>
      <body>
        ${header}
        ${htmlBody}
        ${signatures}
        ${footer}
      </body>
    </html>
  `;

  printWindow.document.write(fullHtml);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => printWindow.print(), 400);
}
